import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            style: {
              background: "#162329",
              color: "#fff",
            },
            success: {
              iconTheme: {
                primary: "#4ade80",
                secondary: "#162329",
              },
            },
            error: {
              iconTheme: {
                primary: "#f87171",
                secondary: "#162329",
              },
            },
          }}
        />
        <div className="w-full flex justify-center">
          <div className="w-full md:w-[32%]">{children}</div>
        </div>
      </body>
    </html>
  );
}
